; *----------------------------------------------*
; *         ParticleEx v1.1 by Fire_Head         *
; *  Visit the link below for more information:  *
; *   https://github.com/Fire-Head/ParticleEx    *
; *----------------------------------------------*

[MAIN]
; Particle system switch.
; PC, PS2, XBOX
Particle=PS2

; On Xbox, the molotov flame effect is not properly centered(it's shifted from the actual center of the fire source), this option fixes this issue.
bFixXboxMolotovBug=True

; On PS2/PC, the game always uses the "flame1" texture instead of "flame5", this option fixes this issue.
; However, because this bug has been present in the game for a long time during its development, this effect was never meant to be used with this texture.
bFixPCPS2Flame5Bug=False

; On PS2, when a car drives through water, it reduces its speed. on PC(also applies to Xbox), this behavior was accidentally cut. This option restores it.
bUsePS2CarPuddlePhysics=True

; Enables the alternative water splash effect for cars(for PS2 particles only). This effect was not used in the final game and appears to be a early iteration of the existing one. If enabled, this will replace the default one.
bUseAltPS2Carsplash=False

; Fixes water splash effect from a car's wheels during rain(for PS2 particles only).
; This effect was broken due to a broken particle ID on PS2. Later on PC it was broken even further due to a failed attempt to fix and optimize it.
bUseNewWheelsWaterSplash=True

; Fixes dark spots on the ground after explosions or molotov. This feature can be seen on pre-release screenshots. It was accidentally broken at some point during development.
bDarkSpotsBugFix=True

; On the PS2, when a car explodes, there's a chance that an explosion jet(trail) will form. On PC, this feature was accidentally broken due to a partial leak of early Vice City code.
; This option restores the correct position of the effect as it was on PS2.
bPS2Jet=True

; A port of "Explosion Jet" from Vice City. If enabled, this will replace the original one.
bVCJet=False

; The maximum number of particles that can appear on the screen.
nParticleLimit=1000
