; *----------------------------------------------*
; *         ParticleEx v1.1 by Fire_Head         *
; *  Visit the link below for more information:  *
; *   https://github.com/Fire-Head/ParticleEx    *
; *----------------------------------------------*

[MAIN]
; Particle system switch.
; PC, PS2, XBOX, XBOX+III
; "XBOX+III" is a mix of Xbox VC and Xbox GTA3. It was created because R* Vienna didn't port the explosion effects from Xbox version of GTA 3.
Particle=XBOX+III

; On Xbox, the molotov flame effect is not properly centered(it's shifted from the actual center of the fire source), this option fixes this issue.
bFixXboxMolotovBug=True

; On PS2/PC, the game always uses the "flame1" texture instead of "flame5", this option fixes this issue.
; However, because this bug has been present in the game for a long time during its development, this effect was never meant to be used with this texture.
bFixFlame5Bug=False

; Fixes dark spots on the ground after explosions or molotov. This feature can be seen on pre-release GTA 3 screenshots. It was accidentally broken at some point during development.
bDarkSpotsBugFix=True

; If enabled, this will hide vanilla waterdrops. This may be useful if you're using neoWaterdrops option from SkyGFX.
bDisableVanillaWaterDrop=False

; If enabled, this will hide vanilla blooddrops. This may be useful if you're using neoWaterdrops option from SkyGFX.
bDisableVanillaBloodDrop=False
